---
- name: Install Python OpenSSL package
  apt:
    pkg: "{{ python2-pkgs }}"
  when: ansible_python_version < '3'

- name: Install Python OpenSSL package
  apt:
    pkg: "{{ python3-pkgs }}"
  when: ansible_python_version > '3'

- name: Install dependencies
  apt:
    pkg: "{{ pkg_dependencies }}"
    update_cache: true

- name: Add Nginx GPG key
  apt_key:
    url: "{{ nginx_gpg_key_url }}"
    state: present

- name: Added Nginx offical repo
  apt_repository:
    repo: "{{ nginx_repo_url }} {{ansible_distribution_release }} nginx "
    state: present
    filename: nginx_repo

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true
