---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: molecule_nginx
    image: ansible/ansible:ubuntu1604py3
    published_ports:
      - 8020:80
provisioner:
  name: ansible
  options:
    vv: true
    diff: true
  config_options:
    defaults:
      stdout_callback: yaml
      callback_whitelist: profile_roles, profile_tasks
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
